# Generated by Django 3.0 on 2020-12-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0002_bmimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=50, null=True)),
                ('food_type', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
