# Generated by Django 3.0 on 2020-12-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0003_foodmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='food_image',
            field=models.ImageField(null=True, upload_to='food_images/'),
        ),
    ]
