# Generated by Django 3.0 on 2020-12-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0004_foodmodel_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='carbohydrates',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='fats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='minerals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='protein',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='vitamin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='water',
            field=models.IntegerField(null=True),
        ),
    ]
