# Generated by Django 3.0 on 2020-12-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0006_auto_20201209_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='fiber',
            field=models.FloatField(null=True),
        ),
    ]
