# Generated by Django 3.0 on 2020-12-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0007_foodmodel_fiber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmodel',
            name='minerals',
        ),
    ]
