# Generated by Django 3.0 on 2020-12-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0009_foodmodel_sugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmodel',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='food_image',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='vitamin',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='water',
        ),
        migrations.CreateModel(
            name='food_referencemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calorieapp.FoodModel')),
            ],
        ),
    ]
