# Generated by Django 3.0 on 2020-12-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0010_auto_20201210_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_referencemodel',
            old_name='food_reference',
            new_name='food_referenc',
        ),
    ]
