# Generated by Django 3.0 on 2020-12-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0011_auto_20201211_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='food_referencemodel',
        ),
    ]
