# Generated by Django 3.0 on 2020-12-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0012_delete_food_referencemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodModel',
        ),
    ]
