# Generated by Django 3.0 on 2020-12-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0013_delete_foodmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Drinks', 'Drinks')], max_length=30, null=True)),
                ('rice_item', models.CharField(choices=[('Rice', 'Rice'), ('Fride-Rice', 'Fride-Rice'), ('Brown-Rice', 'Brown-Rice'), ('Biryani', 'Biryani')], max_length=30, null=True)),
                ('curry', models.CharField(choices=[('Rice', 'Rice'), ('Potato', 'Potato'), ('Brinjal', 'Brinjal'), ('Ladyfinger', 'Ladyfinger'), ('beetroot', 'beetroot'), ('capsicum', 'capsicum'), ('mushrooms', 'mushrooms'), ('brocoli', 'brocoli'), ('cabbage', 'cabbage'), ('carrot', 'carrot'), ('cauliflower', 'cauliflower'), ('cucumber', 'cucumber'), ('garlic', 'garlic'), ('onion', 'onion'), ('pumpkin', 'pumpkin'), ('string beans or green beans', 'string beans or green beans')], max_length=50, null=True)),
                ('salad', models.CharField(choices=[('apple', 'apple'), ('apricot', 'apricot'), ('avocodo', 'avocodo'), ('banana', 'banana'), ('blackberry', 'blackberry'), ('cherry', 'cherry'), ('grapes', 'grapes'), ('green olive', 'green olive'), ('kiwifruit', 'kiwifruit'), ('lemon', 'lemon'), ('lime', 'lime'), ('mango', 'mango'), ('orange', 'orange'), ('papayya', 'papayya'), ('peach', 'peach'), ('pineapple', 'pineapple'), ('plum', 'plum'), ('strawberry', 'strawberry'), ('tomatto', 'tomatto'), ('corn', 'corn'), ('sweet potato', 'sweet potato'), ('watermelon', 'watermelon')], max_length=30, null=True)),
                ('non_veg', models.CharField(choices=[('Chicken', 'Chicken'), ('Egg', 'Egg'), ('Mutton', 'Mutton'), ('Fish', 'Fish'), ('Crabs', 'Crabs')], max_length=30, null=True)),
                ('drinks', models.CharField(choices=[('Water', 'Water'), ('Milk', 'Milk'), ('Butter-Milk', 'Butter-Milk'), ('Coakes', 'Coakes')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_item', models.CharField(choices=[('Rice', 'Rice'), ('Fride-Rice', 'Fride-Rice'), ('Brown-Rice', 'Brown-Rice'), ('Biryani', 'Biryani')], max_length=30, null=True)),
                ('type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Drinks', 'Drinks')], max_length=30, null=True)),
                ('quantity', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
