# Generated by Django 3.0 on 2020-12-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0014_foodmodel_ricemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaloriesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('quantity', models.CharField(max_length=30, null=True)),
                ('protiens', models.CharField(max_length=30, null=True)),
                ('carbos', models.CharField(max_length=30, null=True)),
                ('water', models.CharField(max_length=30, null=True)),
                ('sugar', models.CharField(max_length=30, null=True)),
                ('fiber', models.CharField(max_length=30, null=True)),
                ('fat', models.CharField(max_length=30, null=True)),
                ('vitamin', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
