# Generated by Django 3.0 on 2020-12-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0015_caloriesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caloriesmodel',
            old_name='carbos',
            new_name='food_cal',
        ),
        migrations.RemoveField(
            model_name='caloriesmodel',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='caloriesmodel',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='caloriesmodel',
            name='food',
        ),
        migrations.RemoveField(
            model_name='caloriesmodel',
            name='protiens',
        ),
        migrations.RemoveField(
            model_name='caloriesmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='caloriesmodel',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='caloriesmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='caloriesmodel',
            name='vitamin',
        ),
        migrations.RemoveField(
            model_name='caloriesmodel',
            name='water',
        ),
    ]
