# Generated by Django 3.0 on 2020-12-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0016_auto_20201214_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='rice_item',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('Rice', 'Rice'), ('Fride-Rice', 'Fride-Rice'), ('Brown-Rice', 'Brown-Rice'), ('Biryani', 'Biryani')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ricemodel',
            name='rice_item',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('Rice', 'Rice'), ('Fride-Rice', 'Fride-Rice'), ('Brown-Rice', 'Brown-Rice'), ('Biryani', 'Biryani')], max_length=30, null=True),
        ),
    ]
