# Generated by Django 3.0 on 2020-12-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0017_auto_20201215_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurryItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curry_item', models.CharField(choices=[('Nothing', 'Nothing'), ('Potato', 'Potato'), ('Brinjal', 'Brinjal'), ('Ladyfinger', 'Ladyfinger'), ('beetroot', 'beetroot'), ('capsicum', 'capsicum'), ('mushrooms', 'mushrooms'), ('brocoli', 'brocoli'), ('cabbage', 'cabbage'), ('carrot', 'carrot'), ('cauliflower', 'cauliflower'), ('cucumber', 'cucumber'), ('garlic', 'garlic'), ('onion', 'onion'), ('pumpkin', 'pumpkin'), ('string beans or green beans', 'string beans or green beans')], max_length=30, null=True)),
                ('curry_type', models.CharField(choices=[('Nothing', 'Nothing'), ('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Drinks', 'Drinks')], max_length=30, null=True)),
                ('quantity', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='curry',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('Potato', 'Potato'), ('Brinjal', 'Brinjal'), ('Ladyfinger', 'Ladyfinger'), ('beetroot', 'beetroot'), ('capsicum', 'capsicum'), ('mushrooms', 'mushrooms'), ('brocoli', 'brocoli'), ('cabbage', 'cabbage'), ('carrot', 'carrot'), ('cauliflower', 'cauliflower'), ('cucumber', 'cucumber'), ('garlic', 'garlic'), ('onion', 'onion'), ('pumpkin', 'pumpkin'), ('string beans or green beans', 'string beans or green beans')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='drinks',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('Water', 'Water'), ('Milk', 'Milk'), ('Butter-Milk', 'Butter-Milk'), ('Coakes', 'Coakes')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='food_type',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Drinks', 'Drinks')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='non_veg',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('Chicken', 'Chicken'), ('Egg', 'Egg'), ('Mutton', 'Mutton'), ('Fish', 'Fish'), ('Crabs', 'Crabs')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='salad',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('apple', 'apple'), ('apricot', 'apricot'), ('avocodo', 'avocodo'), ('banana', 'banana'), ('blackberry', 'blackberry'), ('cherry', 'cherry'), ('grapes', 'grapes'), ('green olive', 'green olive'), ('kiwifruit', 'kiwifruit'), ('lemon', 'lemon'), ('lime', 'lime'), ('mango', 'mango'), ('orange', 'orange'), ('papayya', 'papayya'), ('peach', 'peach'), ('pineapple', 'pineapple'), ('plum', 'plum'), ('strawberry', 'strawberry'), ('tomatto', 'tomatto'), ('corn', 'corn'), ('sweet potato', 'sweet potato'), ('watermelon', 'watermelon')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ricemodel',
            name='type',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Drinks', 'Drinks')], max_length=30, null=True),
        ),
    ]
