# Generated by Django 3.0 on 2020-12-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0018_auto_20201215_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_veg_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_veg_item', models.CharField(choices=[('Nothing', 'Nothing'), ('Chicken', 'Chicken'), ('Egg', 'Egg'), ('Mutton', 'Mutton'), ('Fish', 'Fish'), ('Crabs', 'Crabs'), ('Prawns', 'Prawns')], max_length=30, null=True)),
                ('type', models.CharField(choices=[('Nothing', 'Nothing'), ('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Drinks', 'Drinks')], max_length=30, null=True)),
                ('quantity', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='non_veg',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('Chicken', 'Chicken'), ('Egg', 'Egg'), ('Mutton', 'Mutton'), ('Fish', 'Fish'), ('Crabs', 'Crabs'), ('Prawns', 'Prawns')], max_length=30, null=True),
        ),
    ]
